#pragma once

enum GAME_STATE {
	START_MENU,
	PAUSE_MENU,
	LEVEL_COMPLETE_MENU,
	RESUME_LEVEL,
	LOAD_LEVEL,
	IN_LEVEL,
	LEVEL_SELECT,
	NEXT_LEVEL,
	FINISHED_LEVEL,
	PLAYER_DEATH,
	RELOAD_LEVEL,
	TOTAL_EVENTS
};