#pragma once

enum GAME_STATE {
	START_MENU,
	PAUSE_MENU,
	LEVEL_COMPLETE_MENU,
	LEVEL_SELECT,
	HELP_MENU,
	APRIL_FOOLS_MENU,
	RESUME_LEVEL,
	LOAD_LEVEL,
	IN_LEVEL,
	NEXT_LEVEL,
	FINISHED_LEVEL,
	PLAYER_DEATH,
	RELOAD_LEVEL,
	GAME_WIN,
	EXIT_GAME,
	TOTAL_EVENTS
};